{{- range .Values.aplicaciones }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # Usamos $ para llamar a la función global y le sumamos el nombre de la app
  name: {{ include "mi_app_webb.fullname" $ }}-{{ .nombre }}
  labels:
    {{- include "mi_app_webb.labels" $ | nindent 4 }}
spec:
  # Leemos replicas directamente del elemento de la lista
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "mi_app_webb.selectorLabels" $ | nindent 6 }}
      app: {{ .nombre }}
  template:
    metadata:
      labels:
        {{- include "mi_app_webb.selectorLabels" $ | nindent 8 }}
        app: {{ .nombre }}
    spec:
      containers:
        - name: {{ .nombre }}
          # Combinamos el repositorio y el tag que definiste en la lista
          image: "{{ .image.repository }}:{{ .image.tag | default "latest" }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
---
{{- end }}
