{{- range .Values.aplicaciones }}
apiVersion: v1
kind: Service
metadata:
  # Usamos $ para salir del bucle y buscar la función de nombre global
  # Y le añadimos el nombre específico de la aplicación de la lista
  name: {{ include "mi_app_webb.fullname" $ }}-{{ .nombre }}
  namespace: {{ .namespace | default "default" }}  # <<<< ESTA ES LA LÍNEA
  labels:
    {{- include "mi_app_webb.labels" $ | nindent 4 }}
spec:
  # Aquí ya no usamos .Values, porque estamos DENTRO de la lista
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    # Usamos $ para las etiquetas globales y .nombre para filtrar el pod correcto
    {{- include "mi_app_webb.selectorLabels" $ | nindent 4 }}
    app: {{ .nombre }}
---
{{- end }}
